name: "Zenn Metadata Updater"
description: "Update Zenn article metadata and create a pull request."
branding:
  icon: refresh-cw
  color: blue
author: "Futa Hirakoba <korosuke613613@gmail.com>"
inputs:
  github-token:
    required: false
    description: "A GITHUB_TOKEN."
    default: ${{ github.token }}
  commit-sha:
    required: false
    description: "Git commit SHA"
  dry-run: # change this
    required: false
    description: "A boolean, if true, no push or pull request will be created. (default: false)"
    default: "false"
  title:
    required: false
    description: "A title of Zenn article."
  emoji:
    required: false
    description: "An emoji of Zenn article."
  type:
    required: false
    description: "A type of Zenn article."
  topics:
    required: false
    description: "A list of topic of Zenn article."
  published:
    required: false
    description: "A boolean of published of Zenn article. (default: true)"
    default: "true"
  published-at:
    required: false
    description: "A date of published of Zenn article. Don't use auto_generate_published_at option if this option is set.  (default: undefined)"
  auto-generate-published-at:
    required: false
    description: "next_business_day_<HH> (ex: next_business_hour_09), next_day_<HH> or undefined. Don't use published_at option if this option is set. (default: undefined)"
  force-push:
    required: false
    description: "A boolean, if true, override the push to the existing branch. (default: true)"
    default: "true"
  validate:
    required: false
    description: "A boolean, if true, validation of metadata is performed. (default: false)"
    default: "false"
  validate-only:
    required: false
    description: "A boolean, if true, only validation of metadata is performed. (default: false)"
    default: "false"
runs:
  using: "node20"
  pre: "dist/pre.js"
  main: "dist/index.js"
