name: Renovate dry-run

on:
  pull_request:
    paths:
      - "renovate.json"
      - ".github/workflows/renovate-dry-run.yaml"

jobs:
  renovate-dry-run:
    permissions:
      contents: read # required by actions/checkout
      pull-requests: read # required by renovate, because renovate to read pull request.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: cybozu/renovate-dry-run-action@v2
        with:
          config-file: renovate.json
